version = 1

exclude_patterns = [ "**/dist/**" ]
test_patterns = ["**/test/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
  dependency_file_paths = [ "packages/moon-browser/package.json" , "packages/moon/package.json", "packages/moon-compiler/package.json", "packages/moon-cli/package.json" ]
